### ISSUE TITLE
Keep getting error which running Rselenium

### ISSUE THREAD

**Issue by janeshdev** [ropensci/RSelenium#116]
The message which I got after using the following R code is as follows: 
```
library(RSelenium)

RSelenium::checkForServer()
RSelenium::startServer()
mybrowser <- remoteDriver(browser = "firefox")
mybrowser$open()
```

Selenium message:Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: WIN10
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'DSI-PC', ip: '192.168.11.3', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_111'
Driver info: driver.version: FirefoxDriver

Error: 	 Summary: UnknownError
 	 Detail: An unknown server-side error occurred while processing the command.
 	 class: org.openqa.selenium.WebDriverException
	 Further Details: run errorDetails method

**Comment by johndharrison** [comment]
Selenium cannot find where firefos is installed. You would need to inform selenium
Something like:
```
eCaps <- list("firefox_binary" = "C://Program Files (x86)/Mozilla Firefox/firefox.exe")
mybrowser <- remoteDriver(browser = "firefox", extraCapabilities = eCaps)
mybrowser$open()
```
With the selenium server version you list and the firefox you would also need to tell selenium where
geckodriver is if it not in your PATH

```
selServ <- RSelenium::startServer(javaargs = c("-Dwebdriver.gecko.driver=\"C:/Users/john/Documents/geckodriver.exe\""))
```

I would recommend using a Docker container instead as outlined in the Docker vignette
http://rpubs.com/johndharrison/RSelenium-Docker

**Comment by janeshdev** [comment]
Hi I was following the rupbs document and get stuck on `docker pull selenium/....` as shown in figure below. 


![image](https://cloud.githubusercontent.com/assets/3325086/21703436/f7f89714-d366-11e6-9e61-d8e8b16305e4.png)

on R I am getting the following error: 

```
> mybrowser$open()
[1] "Connecting to remote server"
Error in checkError(res) : 
  Couldnt connect to host on http://localhost:4444/wd/hub.
  Please ensure a Selenium server is running.
```

Thanks.

**Comment by johndharrison** [comment]
Seems like a issue with your install of Docker.

**Comment by janeshdev** [comment]
The error that I am getting now is as follows: 

```
> remote_driver$open(silent=T)

Selenium message:The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases

Error: 	 Summary: UnknownError
 	 Detail: An unknown server-side error occurred while processing the command.
 	 class: java.lang.IllegalStateException
	 Further Details: run errorDetails method
```

Not sure what caused this error. Have you had such issue before?

**Comment by johndharrison** [comment]
please see #81

**Comment by janeshdev** [comment]
Thank you. Finally it worked after adding gecko to the system variable. I used as follows: 
![image](https://cloud.githubusercontent.com/assets/3325086/21727926/7dd937a8-d3f8-11e6-8441-2e6a593083e1.png)

Probably it is not a good idea to specify the variable name value from `Downloads` folder. But I will fix that later. I am glad `Rselenium` is finally working. None of the other methods worked for me.

**Comment by janeshdev** [comment]
It seems to work for that one instance. Now, I am again getting the same error: 

```
> remDr <- remoteDriver( browserName="firefox", port=4455 )
> remDr$open()
[1] "Connecting to remote server"

Selenium message:The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases

Error: 	 Summary: UnknownError
 	 Detail: An unknown server-side error occurred while processing the command.
 	 class: java.lang.IllegalStateException
	 Further Details: run errorDetails method
```
java.exe looks like following: 

```
10:26:48.655 INFO - Selenium build info: version: '3.0.1', revision: '1969d75'
10:26:48.655 INFO - Launching a standalone Selenium Server
2017-01-06 10:26:48.673:INFO::main: Logging initialized @250ms
10:26:48.713 INFO - Driver class not found: com.opera.core.systems.OperaDriver
10:26:48.713 INFO - Driver provider com.opera.core.systems.OperaDriver registration is skipped:
Unable to create new instances on this machine.
10:26:48.713 INFO - Driver class not found: com.opera.core.systems.OperaDriver
10:26:48.713 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
10:26:48.717 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform WIN10
2017-01-06 10:26:48.743:INFO:osjs.Server:main: jetty-9.2.15.v20160210
2017-01-06 10:26:48.766:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@100fc185{/,null,AVAILABLE}
2017-01-06 10:26:48.952:INFO:osjs.ServerConnector:main: Started ServerConnector@26653222{HTTP/1.1}{0.0.0.0:4455}
2017-01-06 10:26:48.953:INFO:osjs.Server:main: Started @530ms
10:26:48.953 INFO - Selenium Server is up and running
10:26:55.453 INFO - SessionCleaner initialized with insideBrowserTimeout 0 and clientGoneTimeout 1800000 polling every 180000
10:26:55.476 INFO - Executing: [new session: Capabilities [{nativeEvents=true, browserName=firefox, javascriptEnabled=true, version=, platform=ANY}]])
10:26:55.481 INFO - Creating a new session for Capabilities [{nativeEvents=true, browserName=firefox, javascriptEnabled=true, version=, platform=ANY}]
10:26:55.509 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'DSI-PC', ip: '192.168.99.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_111'
Driver info: driver.version: unknown
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
        at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
        at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
        at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:131)
        at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
        at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:36)
        at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
        at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:189)
        at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:222)
        at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:184)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:150)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'DSI-PC', ip: '192.168.99.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_111'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:96)
        at org.openqa.selenium.remote.server.FirefoxDriverProvider.newInstance(FirefoxDriverProvider.java:64)
        at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:209)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:86)
        ... 9 more
Caused by: java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases
        at com.google.common.base.Preconditions.checkState(Preconditions.java:199)
        at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:109)
        at org.openqa.selenium.firefox.GeckoDriverService.access$000(GeckoDriverService.java:37)
        at org.openqa.selenium.firefox.GeckoDriverService$Builder.findDefaultExecutable(GeckoDriverService.java:95)
        at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:296)
        at org.openqa.selenium.firefox.FirefoxDriver.createCommandExecutor(FirefoxDriver.java:277)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:247)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:242)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:135)
        ... 14 more
10:26:55.516 WARN - Exception: The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases

```

**Comment by janeshdev** [comment]
Finally I was able to fix the issue by reinstalling `docker` and following the instructions in http://rpubs.com/johndharrison/RSelenium-Docker . 

Thanks for bearing with my issues.
