### ISSUE TITLE
Element is not clickable issue

### ISSUE THREAD

**Issue by ganeshnikumbh** [ropensci/RSelenium#92]
Hi,

I am getting below error while running a for loop which downloads data from 230 pages. error comes at random times. first it came when the 100th page was clicked and then it came on 67th page. below is the error
16:00:54.791 INFO [97] org.openqa.selenium.remote.server.DriverServlet - Executing: [click: 217 [[FirefoxDriver: firefox on WINDOWS (e00d2916-5656-4c1d-b46f-018327d9d50b)] -> name: ctl00$ContentBody$rgridCDPList$ctl00$ctl03$ctl01$ctl30]])
16:00:55.025 WARN [97] org.openqa.selenium.remote.server.DriverServlet - Exception thrown
org.openqa.selenium.WebDriverException: Element is not clickable at point (369, 360). Other element would receive the click: <span id="loaderLabel"></span>
Command duration or timeout: 110 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: my_laptop_name, ip: my_system_ip, os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=47.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: e00d2916-5656-4c1d-b46f-018327d9d50b
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:85)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke(EventFiringWebDriver.java:335)
	at com.sun.proxy.$Proxy2.click(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.click(EventFiringWebDriver.java:348)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.openqa.selenium.remote.server.KnownElements$1.invoke(KnownElements.java:64)
	at com.sun.proxy.$Proxy3.click(Unknown Source)
	at org.openqa.selenium.remote.server.handler.ClickElement.call(ClickElement.java:30)
	at org.openqa.selenium.remote.server.handler.ClickElement.call(ClickElement.java:1)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
16:00:55.025 WARN [97] org.openqa.selenium.remote.server.DriverServlet - Exception: Element is not clickable at point (369, 360). Other element would receive the click: <span id="loaderLabel"></span>
Command duration or timeout: 110 milliseconds

**Comment by johndharrison** [comment]
Please see the discussion on SO:

http://stackoverflow.com/questions/11908249/debugging-element-is-not-clickable-at-point-error

In summary, your element may not be visible, the page is getting refreshed before it is clicking the element or  the element is clickable but there is a spinner/overlay on top of it. 

The problem will be specific to the page you are attempting to interact.

**Comment by ganeshnikumbh** [comment]
Hi John,
what worries me is the error coming on random pages. As I mentioned earlier, the first time when the code ran, I got the error on 100th page. Second time on 69th page and next 58th page. I am also watching the test when it is running and I can visually see the clickable area.. I tried changing the browser to IE, and not I am getting error "Exception: Unable to find element with id == ctl00_ContentBody_rgridCDPList_ctl00" on random pages every time I run the test. below is a code snippet where I am getting the error:


for(i in 1:total_pages[2])
  {        
    print(i)
    Sys.sleep(3)
    elem <- remDr$findElement(using="id", value="ctl00_ContentBody_rgridCDPList_ctl00") # get big table in text string
    elemtxt <- elem$getElementAttribute("outerHTML")[[1]]
       b <- read_html(elemtxt)
    
    data <- b %>%
      html_nodes("table") %>%
      .[[1]] %>%
      html_table(fill=TRUE)
    
    data1 <- data[c(-1,-2,-3),c(-1,-16,-17,-18)]
    finaldata <- rbind(finaldata,data1)
    
    if(round_any(as.numeric(total_pages[2]),10,floor) == as.numeric(total_pages[2]))
    {
      pg_no <<- as.numeric(total_pages[2])-10
    }else
    {
      pg_no <<- round_any(as.numeric(total_pages[2]),10,floor)
    }
    
    
    if(i < 11 || i > pg_no)
    {
      dt <- remDr$findElement(using="name", value="ctl00$ContentBody$rgridCDPList$ctl00$ctl03$ctl01$ctl28") # get big table in text string
      dt$clickElement()
      Sys.sleep(10)
    }else
    {
      dt <- remDr$findElement(using="name", value="ctl00$ContentBody$rgridCDPList$ctl00$ctl03$ctl01$ctl30") # get big table in text string
      dt$clickElement()
      Sys.sleep(10)
    }
    
  }

**Comment by johndharrison** [comment]
The website is most likely dynamically loading content. If your `findElement` calls are returning as element not found you can try setting the implicit wait timeout (`remDr$setImplicitWaitTimeout(setImplicitWaitTimeout)`). If not called it defaults to a value of zero so if the element is not present it returns the exception. Setting it to 10000 the driver will wait for upto 10 seconds for the element to appear.

**Comment by ganeshnikumbh** [comment]
Issue solved after using css selector in findelement
